"""
Configuration settings for the RAG Agent - TT Account
Account: tt
Project: dvlm-adk-lab
Region: us-west1

Generated by deploy_env_config.py on 2026-02-28 21:39:06
DO NOT EDIT MANUALLY — regenerate with:
  python backend/deploy_env_config.py --env environments/tt.yaml
"""

import os

# Account identifier
ACCOUNT_NAME = "tt"
ACCOUNT_DESCRIPTION = "Tt Account"

# Vertex AI settings
PROJECT_ID = os.environ.get("PROJECT_ID", "dvlm-adk-lab")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-west1")

# RAG settings
DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_TOP_K = 3
DEFAULT_DISTANCE_THRESHOLD = 0.5
DEFAULT_EMBEDDING_MODEL = "publishers/google/models/text-embedding-005"
DEFAULT_EMBEDDING_REQUESTS_PER_MIN = 1000

# Corpus to GCS Bucket Mapping
CORPUS_TO_BUCKET_MAPPING = {
    "tech-articles": "techtrend-articles",
    "product-docs": "techtrend-product-documentation",
    "research-papers": "techtrend-research",
}

# Account-specific settings
ORGANIZATION_DOMAIN = "techtrend.com"
DEFAULT_CORPUS_NAME = "techtrend-general"
